In [1]:
import numpy as np

## Creating Numpy Array Using Python list

In [5]:
# Creating 1D Array

arr1 = np.array([1,2,3,4,5])
print(arr1,type(arr1),arr1.dtype,arr1.shape)

arr2 = np.array([1,2,3,4,5,"Tulsi"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr3 = np.array([1,2,3,4,5,{"name" : "Tulsi"}])
print(arr3,type(arr3),arr3.dtype,arr3.shape)

# Creating 2D Array

arr_2D = np.array([[1,2,3,4],[5,6,7,10]])
print(arr_2D,arr_2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'Tulsi'] <class 'numpy.ndarray'> <U21 (6,)
[1 2 3 4 5 {'name': 'Tulsi'}] <class 'numpy.ndarray'> object (6,)


## Creating Numpy array from scratch

In [27]:
arr1 = np.zeros((3,4),dtype="int64")  # Fill with zeores
print(arr1,"\n",arr1.shape)

arr2 = np.ones((4,4),dtype="int64")  # Fill with Ones
print(arr2,"\n",arr2.shape)

arr3 = np.full((4,3),100,dtype="int64") #Fill with Specified Value
print(arr3,"\n",arr3.shape)

arr4 = np.eye(4,dtype=int)  # Creates Identity Matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,10,2)   # Similar Like Python Range
print(arr5,arr5.shape)

arr6 = np.linspace(1,100,10,dtype=int) # create array with equally spaced values
print(arr6)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 
 (3, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 
 (4, 4)
[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] 
 (4, 3)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] (4, 4)
[1 3 5 7 9] (5,)
[  1  12  23  34  45  56  67  78  89 100]
