In [1]:
import numpy as np

In [4]:
# MultiDimenshional
arr2D = np.array([[1,2,3],[4,5,6]])

In [9]:
print(np.sum(arr2D))

# Sum Of All Columns

print(np.sum(arr2D,axis=0))

# Sum of Rows
print(np.sum(arr2D,axis=1))

21
[5 7 9]
[ 6 15]


In [12]:
# Slicing In 2D Array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr[0:2,1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [16]:
# 3D Array

arr = np.array([[[255,0,0],[249,130,0],[130,150,170]],[[0,0,255],[0,255,0],[10,15,100]],[[150,180,170],[190,200,240],[0,255,255]]])
print(arr)
print(arr.shape)
print(arr.size)

print(arr[1][2][2])
print(arr[1,2,2])

[[[255   0   0]
  [249 130   0]
  [130 150 170]]

 [[  0   0 255]
  [  0 255   0]
  [ 10  15 100]]

 [[150 180 170]
  [190 200 240]
  [  0 255 255]]]
(3, 3, 3)
27
100
100


In [18]:
# Slicing
arr[:,:,0:1]

array([[[255],
        [249],
        [130]],

       [[  0],
        [  0],
        [ 10]],

       [[150],
        [190],
        [  0]]])