In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [18]:
print(arr.shape)  # Provides Dimenshions
print(arr.size) # Provides Number of eles
print(arr.dtype) # Provides data type of the array
print(arr.ndim) # provides how many dimenshion are in array(here row and col)

float_arr = arr.astype(np.float64)  #converts one data type to another
print(float_arr)

str_arr = arr.astype(int)  #converts one data type to another
print(str_arr)

(2, 4)
8
int64
2
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
[[1 2 3 4]
 [5 6 7 8]]
