In [1]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6,127])
print(arr.dtype)

# Integer Downcast
arr = np.array([1,2,3,4,5,6,127],dtype="int8")
print(arr.dtype)

int8


In [21]:
arr = np.array([1,2,3,4,5,6,19.6])
print(arr.dtype)
print(arr)

float64
[ 1.   2.   3.   4.   5.   6.  19.6]


In [22]:
arr = np.array([1,2,3,4,5,6,19.6,"Tulsi"])
print(arr.dtype)
print(arr)

<U32
['1' '2' '3' '4' '5' '6' '19.6' 'Tulsi']


In [23]:
arr = np.array([1,2,3,4,5,6,19.6,False])
print(arr.dtype)
print(arr)

float64
[ 1.   2.   3.   4.   5.   6.  19.6  0. ]


In [24]:
arr = np.array([True,False])
print(arr.dtype)
print(arr)

bool
[ True False]


In [26]:
arr = np.array([1,2,3,4,5,6,19.6,False,3 + 5j])
print(arr.dtype)
print(arr)

print(arr + (6 + 5j))

complex128
[ 1. +0.j  2. +0.j  3. +0.j  4. +0.j  5. +0.j  6. +0.j 19.6+0.j  0. +0.j
  3. +5.j]
[ 7.  +5.j  8.  +5.j  9.  +5.j 10.  +5.j 11.  +5.j 12.  +5.j 25.6 +5.j
  6.  +5.j  9. +10.j]


In [30]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
3
