In [2]:
import numpy as np

In [3]:
# Aggregation Functions

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #return index of minimum value
print(np.argmax(arr))  #return index of maximum value
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))

# varian == square(std)
print(np.square(np.std(arr)))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0000000000000004
2.0


In [9]:
# Power Functions

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [14]:
# Log
print(np.log(arr))
print(np.log2(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [21]:
# Rounding
print(np.round(10.7))
print(np.ceil(10.5))
print(np.floor(10.5))
print(np.trunc(10.5))

11.0
11.0
10.0
10.0


In [26]:
# some other functions
arr = [1,2,3,4,1,7,-9,10,4,-2]
print(np.unique(arr))  #gives Unique Value
print(np.sort(arr))
print(np.abs(arr))

[-9 -2  1  2  3  4  7 10]
[-9 -2  1  1  2  3  4  4  7 10]
[ 1  2  3  4  1  7  9 10  4  2]
