In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
# Reshape Array ---> Changes the dimenshion of array
print(arr)
reshaped = arr.reshape((4,2))
print(reshaped,reshaped.shape) 

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] (4, 2)


In [13]:
# Flattern Array -> converts nd array into 1d
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6 7 8 9 0 1 2]


In [23]:
# Indexing

arr = np.arange(1,10)

for i in range(len(arr)):
    print(arr[i],end=" ")
    
print()

arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][2])

# Fancy Indexing
arr = np.arange(1,20,2)
print(arr)
print(arr[[i for i in range(10) if i % 2 == 0]]) #accessing Multiple Elements Simultaneously

# Boolean indexing

print(arr[arr % 3 == 0])

1 2 3 4 5 6 7 8 9 
6
[ 1  3  5  7  9 11 13 15 17 19]
[ 1  5  9 13 17]
[ 3  9 15]


In [29]:
# Slicing
arr = np.array([1,2,3,4,5,6])
print(arr[2:5])
print(arr[2:5:2])

[3 4 5]
[3 5]


In [34]:
# Difference between python slicing and numpy slicing (python creates copy vs numpy creates view)

print("Python List Slicing")
nums = [1,2,3,4,5]
nums2 = nums[1:4]
print(nums2)
nums2[0] = 10
print(nums2)
print(nums)  # Not Any Change in Actual data

print()

print("Numpy Array Slicing")
nums = np.array([1,2,3,4,5])
nums2 = nums[1:4]
print(nums2)
nums2[0] = 10
print(nums2)
print(nums)  #  Change in Actual data

print("Numpy Array Copy Slicing")
nums = np.array([1,2,3,4,5])
nums2 = nums[1:4].copy()
print(nums2)
nums2[0] = 10
print(nums2)
print(nums)  #  NO Change in Actual data

Python List Slicing
[2, 3, 4]
[10, 3, 4]
[1, 2, 3, 4, 5]

Numpy Array Slicing
[2 3 4]
[10  3  4]
[ 1 10  3  4  5]
Numpy Array Copy Slicing
[2 3 4]
[10  3  4]
[1 2 3 4 5]
