In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr ** 2)
print(arr + 10)

[ 1  4  9 16 25]
[11 12 13 14 15]


In [8]:
# Broadcasting

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([4])

print(arr1.shape)
print(arr2.shape)
print(arr1 * arr2)

(3, 2)
(1,)
[[ 4  8]
 [12 16]
 [20 24]]


In [11]:
# Not Allowed broadcasting
# # arr1 = np.array([[1,2,3],[4,5,6]])  
# # arr2 = np.array([[1,2],[3,4]])
# print(arr1.shape)
# print(arr1.shape)
# print(arr1 * arr2)

arr1 = np.array([[1,2,3],[4,5,6]])  
arr2 = np.array([[2],[4]])
print(arr1.shape)
print(arr1.shape)
print(arr1 * arr2)

(2, 3)
(2, 3)
[[ 2  4  6]
 [16 20 24]]


In [20]:
# Standard Normalization
arr = np.array([[1,2,3],[4,5,6]])
std_dev = np.sqrt(np.sum(((arr - np.mean(arr)) ** 2 )) / arr.size)

# Normalization
norm_arr = (arr - np.mean(arr)) / std_dev

In [21]:
print(std_dev)
print(np.std(arr))
print(norm_arr)

1.707825127659933
1.707825127659933
[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [22]:
print(np.mean(norm_arr))

-3.700743415417188e-17
